module.exports = {
    negativo: "",
    positivo: "",
    estrella: "",
    mas: "",
    menos: "",
    warning: "",
    discord_mod: "",
    guidelines_azul: "",
    martillo: "",
    volumenes: "",
    escudo_azul: "",
    espadas_azul: "",
    carta_azul: "",
    puntos: "",
    corona_azul: "",
    servers_azul: "",
    xmartillo_azul: "",
    corona_naranja: "",
    rueda: "",
    cargando: "",
    guion: "",
    llave: ""
}